swagger: '2.0'
info:
  version: 0.1.0
  title: idm
  description: Learners Guild Identity Management System
  termsOfService: 'https://learnersguild.org/legal/terms'
  contact:
    name: Jeffrey Wescott
    email: jeffrey@learnersguild.org
  license:
    name: UNLICENSED
basePath: /
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    get:
      description: Returns all users from the system that the user has access to
      x-swagger-router-controller: Users
      operationId: findUsers
      produces:
        - application/json
      parameters:
        - name: id
          in: query
          description: return only users that match the given id
          required: false
          type: string
          format: UUID
        - name: name
          in: query
          description: return only users that match the given name
          required: false
          type: string
        - name: email
          in: query
          description: return only users that match the given email
          required: false
          type: string
          format: email
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        '200':
          description: user response
          schema:
            type: array
            items:
              $ref: '#/definitions/user'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /users/current:
    get:
      description: Returns the currently signed-in user
      x-swagger-router-controller: Users
      operationId: getCurrentUser
      produces:
        - application/json
      responses:
        '200':
          description: user response
          schema:
            $ref: '#/definitions/user'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  '/users/{id}':
    get:
      description: 'Returns a user based on a single ID'
      x-swagger-router-controller: Users
      operationId: getUserById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of user to fetch
          required: true
          type: string
          format: UUID
      responses:
        '200':
          description: user response
          schema:
            $ref: '#/definitions/user'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  user:
    type: object
    description: A user
    required:
      - id
      - name
      - email
    properties:
      id:
        type: string
        format: UUID
      name:
        type: string
      email:
        type: string
        format: email
  errorModel:
    type: object
    description: Error information returned by an unsuccessful API call.
    required:
      - code
      - message
    properties:
      code:
        type: string
      message:
        type: string
